### ISSUE TITLE
Multi-threaded usage bug in 5.6

### ISSUE THREAD

**Issue by phatcher** [object/Simple.OData.Client#566]
There's a bug in 5.6 related to multi-threaded usage of the library in .NET Framework e.g. from within a web site, this can cause the site to deadlock as the request doesn't get back to the ASP.NET worker thread that issued it. 

NET Core is not affected since it's doesn't use thread synchronization in the same way.

This was caused by the line `_metadataCache = InitializeMetadataCache().Result;` in Session which I introduced as part of the ITypeCache changes.

I've fixed it with the following changes...

1. Split the ITypeCache initialization from that of EdmMetadataCache, as we need the ITypeCache before we've retrieved metadata.
2. Revert to initializing EdmMetadataCache in the Session constructor if a document is provided
3. Changed EdmMetadataCache internals to use ConcurrentDictionary and synchronize requests so multiple threads don't request the same metadata in parallel.

It's difficult to write a breaking test due to the multi-threaded nature of the bug, so I'm posting this so if someone has the same problem it's a bit clearer what's going on

**Comment by Trockey** [comment]
I found it hangs for version 5.6, 5.5, 5.4  while call ex. FindEntryAsync on ASP.NET. For WinForm, it hangs too. It looks like problem you described. The same code for .NET Core works fine.

**Comment by object** [comment]
Good finding. It's important not to call Result or Wait methods from the library because of the problem you described.

**Comment by Trockey** [comment]
Some additional findings:

I tested both WinForms and ASP.NET (not Core).
I called FindEntryAsync async method only, **without** Result method.

And FindEntryAsync hangs for specific version:
for **WinForm** It hangs for 5.6 (for 5.5 and below, it works properly),
for **ASP.NET** It hangs for 5.3 (for 5.2 and below, it works properly).

**Comment by object** [comment]
I just pushed the version 5.6.1 with recent Paul's changes. Benchmark results are also published, and they are improved indeed.
I also checked the source code, and yes, the only place in the library where .Wait or .Result is called is the sync version of GetStream in ODataResponseMessage. But this is legacy and and  sync by design, nothing to do about it, there is GetStreamAsync method to be used. It's a part of IODataResponseMessageAsync interface, so we can't remove the method.

**Comment by Trockey** [comment]
> @Trockey Try ASP.NET for the current tip of v5, on our project for 5.6 it worked fine when talking to one OData endpoint but when I started to talk to the second endpoint, it hung as the metadata retrieve call never returned to the originating thread.
> 
> There's only one call to .Result in the library currently, apart from in tests which is inside ODataResponseMessage.GetStream
> 
> I might remove that as it seems to be just legacy and re-code the tests to all be async - @object that ok with you?
> 
> That way we know the library is "clean" and we can keep it that way.

Thank you for you information.

I used WinForm and WebForms (not a .NET Core).
In my case, I used Result, once. With the **only one** endpoint. It hanged. Then, I changed it to NOT use Result, but FindEntryAsync only.  Still hanged. I was sure I do something wrong, but ... when I installed previous versions of Simple.OData.Client (5.2 or below for WebForm) - it started to work properly.

**Comment by object** [comment]
@trockey did you try the latest version? 5.6.1?
